### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by danim80** [vicenteguerra/git-deploy#16]
I have a problem, git deploy says *** AUTO PULL SUCCESFUL *** but no files have been pulled.

**Comment by evansharp** [comment]
Probably the same issue as #13 ...

Reading the `deploy.php`, ln. 66-68:
```
// pull
chdir(DIR);
shell_exec(GIT . " pull");
```
This comes after the logfile is written, so errors with the actual pull or the AFTER_PULL actions are not logged.

Checking the system log, I see:
```
error: cannot open .git/FETCH_HEAD: Permission denied
```

I'm thinking since the script is executing the `git` command, the php user ("www-data" on apache) will need to have write access to the repo directory and  /.git/. I'm going to play with repo group ownerships and see what I can do.

**Comment by evansharp** [comment]
My suspicion is confirmed by this relevant blog post:
https://jondavidjohn.com/git-pull-from-a-php-script-not-so-simple/
I'm testing `www-data` group ownership on the repository as a solution, but it would be much cleaner to work this step into the php.

**Comment by evansharp** [comment]
Confirmed that webserver write access is the problem. 

Created PR #17 to add instruction to the README for this and also improved the logging to identify this issue for people better.

**Comment by danim80** [comment]
Sorry, there was a problem with the Apache user not having the ssh key. Everytime the script executed Git pull was asking the password.

It is working now. Thank you.
